name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Build with Gradle
      run: ./gradlew spotlessCheck lintRelease bundleRelease assembleRelease --stacktrace

    - name: Android Sign
      uses: Tlaster/android-sign@v1.2.1
      with:
        releaseDirectory: |
          app/build/outputs/apk/release
          app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        output: build/release/signed
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload build outputs
      uses: actions/upload-artifact@v2
      with:
        name: build-outputs
        path: ./build/release/signed
        
    - name: Upload build reports
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: ./app/build/reports
